import { supervisorRepository } from '../repositories/supervisor.repository';

export const supervisorService = {
  getDashboard: supervisorRepository.getDashboard,
  getWallboard: supervisorRepository.getWallboard,
  listAgents: supervisorRepository.listAgents,
  listQueues: supervisorRepository.listQueues,
  listLiveCalls: supervisorRepository.listLiveCalls,
  getCallTimeline: supervisorRepository.getCallTimeline,
  listen: supervisorRepository.listen,
  whisper: supervisorRepository.whisper,
  barge: supervisorRepository.barge,
  takeOver: supervisorRepository.takeOver,
  hangUp: supervisorRepository.hangUp,
  transfer: supervisorRepository.transfer,
  endSupervision: supervisorRepository.endSupervision,
  pauseAgent: supervisorRepository.pauseAgent,
  resumeAgent: supervisorRepository.resumeAgent,
  forceLogout: supervisorRepository.forceLogout,
  moveAgent: supervisorRepository.moveAgent,
  pauseQueue: supervisorRepository.pauseQueue,
  resumeQueue: supervisorRepository.resumeQueue,
  overflowQueue: supervisorRepository.overflowQueue,
  emergencyCloseQueue: supervisorRepository.emergencyCloseQueue,
  emergencyStop: supervisorRepository.emergencyStop,
  searchRecordings: supervisorRepository.searchRecordings,
  getRecordingUrl: supervisorRepository.getRecordingUrl,
  annotateRecording: supervisorRepository.annotateRecording,
  listCoaching: supervisorRepository.listCoaching,
  addCoaching: supervisorRepository.addCoaching,
  getReports: supervisorRepository.getReports,
};
