-- Kamailio usrloc persistence schema (Remediation H-06)
-- Canonical file: infrastructure/kamailio/postgres/bootstrap-usrloc.sql
-- Apply manually:
--   psql "$KAMAILIO_USRLOC_DB_URL" -f infrastructure/kamailio/postgres/bootstrap-usrloc.sql
-- Docker entrypoint runs init-kamailio-db.sh automatically when persistence=postgres.
