export const queryKeys = {
  platform: {
    dashboard: () => ['platform', 'dashboard'] as const,
    tenants: (filters?: Record<string, string>) => ['platform', 'tenants', filters ?? {}] as const,
    tenant: (id: string) => ['platform', 'tenants', id] as const,
    billing: () => ['platform', 'billing', 'summary'] as const,
    carriers: () => ['platform', 'carriers'] as const,
    roles: (tenantId?: string) => ['platform', 'roles', tenantId ?? 'all'] as const,
    permissions: (tenantId?: string) => ['platform', 'permissions', tenantId ?? 'all'] as const,
    audit: (params?: Record<string, string>) => ['platform', 'audit', params ?? {}] as const,
    users: (search?: string) => ['platform', 'users', search ?? ''] as const,
    settings: () => ['platform', 'settings'] as const,
    apiKeys: (tenantId?: string) => ['platform', 'api-keys', tenantId ?? 'all'] as const,
    search: (q: string) => ['platform', 'search', q] as const,
    organization: (tenantId: string) => ['platform', 'organization', tenantId] as const,
  },
  ops: {
    dashboard: (tenantId?: string) => ['ops', 'dashboard', tenantId ?? 'global'] as const,
    health: () => ['ops', 'health'] as const,
    kamailio: () => ['ops', 'kamailio'] as const,
    rtpengine: () => ['ops', 'rtpengine'] as const,
    redis: () => ['ops', 'redis'] as const,
    postgres: () => ['ops', 'postgres'] as const,
    carriersHealth: () => ['ops', 'carriers-health'] as const,
    audit: (params?: Record<string, string>) => ['ops', 'audit', params ?? {}] as const,
    sipRegistrations: (params?: Record<string, string>) => ['ops', 'sip-registrations', params ?? {}] as const,
    trace: (params?: Record<string, string>) => ['ops', 'trace', params ?? {}] as const,
  },
  tenant: {
    dashboard: () => ['tenant', 'dashboard'] as const,
    users: (search?: string) => ['tenant', 'users', search ?? ''] as const,
    devices: (search?: string) => ['tenant', 'devices', search ?? ''] as const,
    device: (id: string) => ['tenant', 'devices', 'detail', id] as const,
    firmware: () => ['tenant', 'provisioning', 'firmware'] as const,
    provisioningTemplates: () => ['tenant', 'provisioning', 'templates'] as const,
    extensions: (search?: string) => ['tenant', 'extensions', search ?? ''] as const,
    dids: (search?: string) => ['tenant', 'dids', search ?? ''] as const,
    queues: () => ['tenant', 'queues'] as const,
    ivrs: () => ['tenant', 'ivrs'] as const,
    ivr: (id: string) => ['tenant', 'ivrs', id] as const,
    ivrReports: (id: string, days: number) => ['tenant', 'ivrs', id, 'reports', days] as const,
    inboundRoutes: () => ['tenant', 'inbound-routes'] as const,
    outboundRoutes: () => ['tenant', 'outbound-routes'] as const,
    timeConditions: () => ['tenant', 'time-conditions'] as const,
    holidayCalendars: () => ['tenant', 'holiday-calendars'] as const,
    announcements: (category?: string) => ['tenant', 'announcements', category ?? 'all'] as const,
    announcementVersions: (id: string) => ['tenant', 'announcements', id, 'versions'] as const,
    audioReports: () => ['tenant', 'audio-reports'] as const,
    mohPlaylists: (scope?: string, language?: string) =>
      ['tenant', 'moh-playlists', scope ?? 'all', language ?? 'all'] as const,
    mohPlaylist: (id: string) => ['tenant', 'moh-playlists', id] as const,
    mohPlaylistVersions: (id: string) => ['tenant', 'moh-playlists', id, 'versions'] as const,
    mohAssignments: () => ['tenant', 'moh-assignments'] as const,
    pagingGroups: (kind?: string) => ['tenant', 'paging-groups', kind ?? 'all'] as const,
    pagingGroup: (id: string) => ['tenant', 'paging-groups', id] as const,
    pagingReports: () => ['tenant', 'paging-reports'] as const,
    dialPlans: () => ['tenant', 'dial-plans'] as const,
    routingMetrics: () => ['tenant', 'routing-metrics'] as const,
    ringGroups: () => ['tenant', 'ring-groups'] as const,
    queueDashboard: () => ['tenant', 'queue-dashboard'] as const,
    voicemail: (search?: string) => ['tenant', 'voicemail', search ?? ''] as const,
    voicemailDetail: (id: string) => ['tenant', 'voicemail', 'detail', id] as const,
    voicemailReports: (days: number) => ['tenant', 'voicemail', 'reports', days] as const,
    voicemailMessages: (id: string, params?: Record<string, unknown>) =>
      ['tenant', 'voicemail-messages', id, params ?? {}] as const,
    conferences: (search?: string) => ['tenant', 'conferences', search ?? ''] as const,
    conference: (id: string) => ['tenant', 'conferences', 'detail', id] as const,
    conferenceLive: (id: string) => ['tenant', 'conferences', 'live', id] as const,
    conferenceReports: (days: number) => ['tenant', 'conferences', 'reports', days] as const,
    routing: () => ['tenant', 'routing'] as const,
    cdr: (params?: Record<string, string>) => ['tenant', 'cdr', params ?? {}] as const,
    recordings: (params?: Record<string, string | number | boolean | undefined>) =>
      ['tenant', 'recordings', params ?? {}] as const,
    recording: (id: string) => ['tenant', 'recordings', 'detail', id] as const,
    recordingReports: (days: number) => ['tenant', 'recordings', 'reports', days] as const,
    recordingPolicies: () => ['tenant', 'recording-policies'] as const,
    presence: (search?: string) => ['tenant', 'presence', search ?? ''] as const,
    contacts: (params?: Record<string, unknown>) => ['tenant', 'contacts', params ?? {}] as const,
    contactDirectory: (search?: string) => ['tenant', 'contacts', 'directory', search ?? ''] as const,
    contactFavorites: () => ['tenant', 'contacts', 'favorites'] as const,
    speedDial: () => ['tenant', 'contacts', 'speed-dial'] as const,
    blfPanels: (mine?: boolean) => ['tenant', 'blf', 'panels', mine ?? false] as const,
    blfLamps: (panelId: string) => ['tenant', 'blf', 'lamps', panelId] as const,
    receptionDashboard: () => ['tenant', 'reception', 'dashboard'] as const,
    receptionCalls: () => ['tenant', 'reception', 'calls'] as const,
    receptionParking: (lotId?: string) => ['tenant', 'reception', 'parking', lotId ?? 'all'] as const,
    receptionReports: (days: number) => ['tenant', 'reception', 'reports', days] as const,
    numberRequests: () => ['tenant', 'number-requests'] as const,
  },
  marketplace: {
    dashboard: () => ['marketplace', 'dashboard'] as const,
    inventory: (filters?: Record<string, string>) => ['marketplace', 'inventory', filters ?? {}] as const,
    favorites: () => ['marketplace', 'favorites'] as const,
    savedSearches: () => ['marketplace', 'saved-searches'] as const,
    notifications: (unreadOnly?: boolean) => ['marketplace', 'notifications', unreadOnly ?? false] as const,
    requests: (status?: string) => ['marketplace', 'requests', status ?? 'all'] as const,
    platformRequests: (status?: string) => ['marketplace', 'platform-requests', status ?? 'all'] as const,
    reports: () => ['marketplace', 'reports'] as const,
  },
  telnyx: {
    dashboard: () => ['telnyx', 'dashboard'] as const,
    syncStatus: () => ['telnyx', 'sync-status'] as const,
    numbers: (filters?: Record<string, string>) => ['telnyx', 'numbers', filters ?? {}] as const,
    number: (id: string) => ['telnyx', 'numbers', id] as const,
    history: (id: string) => ['telnyx', 'history', id] as const,
    searchAvailable: (filters?: Record<string, string>) => ['telnyx', 'search-available', filters ?? {}] as const,
    marketplace: (search?: string) => ['telnyx', 'marketplace', search ?? ''] as const,
    requests: (status?: string) => ['telnyx', 'requests', status ?? 'all'] as const,
  },
  trunks: {
    all: () => ['trunks', 'list'] as const,
  },
  liveCalls: {
    list: (tenantId?: string) => ['live-calls', tenantId ?? 'global'] as const,
  },
  extensions: {
    list: (filters?: Record<string, string>) => ['extensions', filters ?? {}] as const,
  },
  tenants: {
    all: () => ['tenants', 'list'] as const,
  },
  supervisor: {
    dashboard: (tenantId?: string) => ['supervisor', 'dashboard', tenantId ?? 'tenant'] as const,
    wallboard: (tenantId?: string) => ['supervisor', 'wallboard', tenantId ?? 'tenant'] as const,
    agents: (tenantId?: string) => ['supervisor', 'agents', tenantId ?? 'tenant'] as const,
    queues: (tenantId?: string) => ['supervisor', 'queues', tenantId ?? 'tenant'] as const,
    liveCalls: (tenantId?: string) => ['supervisor', 'live-calls', tenantId ?? 'tenant'] as const,
    timeline: (platformUuid: string, tenantId?: string) =>
      ['supervisor', 'timeline', platformUuid, tenantId ?? 'tenant'] as const,
    recordings: (params?: Record<string, string | number | undefined>) =>
      ['supervisor', 'recordings', params ?? {}] as const,
    reports: (tenantId?: string) => ['supervisor', 'reports', tenantId ?? 'tenant'] as const,
    coaching: (callSessionId?: string) => ['supervisor', 'coaching', callSessionId ?? 'all'] as const,
  },
  noc: {
    dashboard: (tenantId?: string) => ['noc', 'dashboard', tenantId ?? 'global'] as const,
    registrations: (params?: Record<string, string | undefined>) => ['noc', 'registrations', params ?? {}] as const,
    dialogs: (tenantId?: string) => ['noc', 'dialogs', tenantId ?? 'global'] as const,
    sipTrace: (params?: Record<string, string | undefined>) => ['noc', 'sip-trace', params ?? {}] as const,
    media: (tenantId?: string) => ['noc', 'media', tenantId ?? 'global'] as const,
    kamailio: () => ['noc', 'kamailio'] as const,
    rtpengine: (tenantId?: string) => ['noc', 'rtpengine', tenantId ?? 'global'] as const,
    carriers: () => ['noc', 'carriers'] as const,
    alerts: (status?: string) => ['noc', 'alerts', status ?? 'all'] as const,
    fraud: (tenantId?: string) => ['noc', 'fraud', tenantId ?? 'global'] as const,
    diagnostics: (platformUuid: string, tenantId?: string) =>
      ['noc', 'diagnostics', platformUuid, tenantId ?? 'tenant'] as const,
  },
  billing: {
    summary: () => ['billing', 'summary'] as const,
  },
} as const;
