import {
  Activity,
  AudioLines,
  Building2,
  Cable,
  CreditCard,
  Database,
  FileText,
  GitBranch,
  Headphones,
  KeyRound,
  LayoutDashboard,
  ListOrdered,
  Mic,
  Network,
  Phone,
  PhoneCall,
  PhoneForwarded,
  PhoneIncoming,
  Radio,
  Route,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  Smartphone,
  Users,
  Voicemail,
  Workflow,
} from 'lucide-react';
import type { ModuleDefinition, NavGroup } from '../../types/navigation';
import { hasPermission } from '../rbac/permissions';

export const NAV_GROUP_LABELS: Record<NavGroup, string> = {
  operations: 'Operations Center',
  carrier: 'Carrier & Numbers',
  platform: 'Platform',
  telephony: 'PBX',
  routing: 'Call Routing',
  analytics: 'Analytics',
  billing: 'Billing',
  infrastructure: 'Infrastructure',
  security: 'Security',
  system: 'System',
};

/** Nav group display order — carrier inventory first for platform operators. */
export const NAV_GROUP_ORDER: NavGroup[] = [
  'operations',
  'carrier',
  'platform',
  'telephony',
  'routing',
  'analytics',
  'billing',
  'infrastructure',
  'security',
  'system',
];

export const MODULES: ModuleDefinition[] = [
  // ── Operations Center ─────────────────────────────────────────────
  {
    id: 'dashboard',
    label: 'Operations Dashboard',
    href: '/dashboard',
    group: 'operations',
    icon: LayoutDashboard,
    permission: 'tenant:user',
    integration: 'bff',
    description: 'Live PBX operations — calls, registrations, tenants, and carrier health.',
    breadcrumb: ['Operations Center', 'Dashboard'],
    apiEndpoints: ['/v1/observability/dashboard'],
  },
  {
    id: 'live-calls',
    label: 'Live Calls',
    href: '/live-calls',
    group: 'operations',
    icon: PhoneIncoming,
    permission: 'tenant:admin',
    integration: 'live',
    description: 'Real-time active call sessions across the platform.',
    breadcrumb: ['Operations Center', 'Live Calls'],
    apiEndpoints: ['/v1/live-calls'],
  },

  // ── Carrier & Numbers (Telnyx primary) ────────────────────────────
  {
    id: 'telnyx-numbers',
    label: 'Telnyx Numbers',
    href: '/telnyx-numbers',
    group: 'carrier',
    icon: PhoneCall,
    permission: 'platform:super_admin',
    integration: 'live',
    primary: true,
    description: 'Platform-wide Telnyx phone number inventory — purchase, assign, and release before tenant allocation.',
    breadcrumb: ['Carrier & Numbers', 'Telnyx Numbers'],
    prismaModels: ['PhoneNumber', 'NumberAssignment'],
    apiEndpoints: ['/v1/carriers/telnyx/numbers'],
  },
  {
    id: 'trunks',
    label: 'SIP Trunks',
    href: '/trunks',
    group: 'carrier',
    icon: Cable,
    permission: 'platform:super_admin',
    integration: 'live',
    description: 'Telnyx SIP trunks, channel capacity, failover, and registration status.',
    breadcrumb: ['Carrier & Numbers', 'SIP Trunks'],
    prismaModels: ['Carrier'],
    apiEndpoints: ['/v1/telecom/carrier/health'],
  },
  {
    id: 'carriers',
    label: 'Carrier Integrations',
    href: '/carriers',
    group: 'carrier',
    icon: GitBranch,
    permission: 'platform:super_admin',
    integration: 'live',
    description: 'Telnyx adapter health, webhooks, and PSTN interconnect configuration.',
    breadcrumb: ['Carrier & Numbers', 'Integrations'],
    prismaModels: ['Carrier'],
    apiEndpoints: ['/v1/telecom/carrier/health', '/v1/webhooks/telnyx'],
  },
  {
    id: 'dids',
    label: 'Tenant DIDs',
    href: '/dids',
    group: 'carrier',
    icon: Phone,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Numbers assigned to this tenant — extensions, IVR, and queue routing.',
    breadcrumb: ['Carrier & Numbers', 'Tenant DIDs'],
    prismaModels: ['PhoneNumber', 'NumberAssignment'],
  },

  // ── Platform ──────────────────────────────────────────────────────
  {
    id: 'tenants',
    label: 'Tenants',
    href: '/tenants',
    group: 'platform',
    icon: Building2,
    permission: 'platform:super_admin',
    integration: 'planned',
    description: 'Multi-tenant organizations, sites, and lifecycle management.',
    breadcrumb: ['Platform', 'Tenants'],
    prismaModels: ['Tenant', 'TenantSettings', 'Site'],
  },
  {
    id: 'organization',
    label: 'Organization',
    href: '/organization',
    group: 'platform',
    icon: Building2,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Current tenant profile, sites, and organization settings.',
    breadcrumb: ['Platform', 'Organization'],
    prismaModels: ['Tenant', 'TenantSettings', 'Site'],
  },
  {
    id: 'users',
    label: 'Users',
    href: '/users',
    group: 'platform',
    icon: Users,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'User accounts, profiles, and site assignments.',
    breadcrumb: ['Platform', 'Users'],
    prismaModels: ['User', 'UserProfile', 'UserSite'],
  },
  {
    id: 'roles',
    label: 'Roles',
    href: '/roles',
    group: 'platform',
    icon: Shield,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Role definitions and permission assignments.',
    breadcrumb: ['Platform', 'Roles'],
    prismaModels: ['Role', 'UserRole'],
  },
  {
    id: 'permissions',
    label: 'Permissions',
    href: '/permissions',
    group: 'platform',
    icon: KeyRound,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Permission catalog for RBAC configuration.',
    breadcrumb: ['Platform', 'Permissions'],
    prismaModels: ['Permission', 'RolePermission'],
  },

  // ── PBX ───────────────────────────────────────────────────────────
  {
    id: 'extensions',
    label: 'Extensions',
    href: '/extensions',
    group: 'telephony',
    icon: Phone,
    permission: 'tenant:admin',
    integration: 'live',
    description: 'Extension numbers, line assignments, and dial plans.',
    breadcrumb: ['PBX', 'Extensions'],
    prismaModels: ['Extension', 'Line'],
    apiEndpoints: ['/v1/extensions'],
  },
  {
    id: 'devices',
    label: 'Devices',
    href: '/devices',
    group: 'telephony',
    icon: Smartphone,
    permission: 'provisioning:admin',
    integration: 'live',
    description: 'Desk phones, registrations, firmware, and MAC inventory.',
    breadcrumb: ['PBX', 'Devices'],
    apiEndpoints: ['/v1/provisioning/devices/enroll'],
    prismaModels: ['Device', 'DeviceAssignment'],
  },
  {
    id: 'sip-accounts',
    label: 'SIP Registrations',
    href: '/sip-accounts',
    group: 'telephony',
    icon: Network,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'SIP endpoint credentials and live registration status.',
    breadcrumb: ['PBX', 'SIP Registrations'],
    prismaModels: ['SIPEndpoint'],
  },
  {
    id: 'provisioning',
    label: 'Provisioning',
    href: '/provisioning',
    group: 'telephony',
    icon: Server,
    permission: 'provisioning:admin',
    integration: 'live',
    description: 'Zero-touch provisioning, templates, and firmware rollout.',
    breadcrumb: ['PBX', 'Provisioning'],
    apiEndpoints: ['/v1/provisioning/devices/*'],
  },

  // ── Call Routing ──────────────────────────────────────────────────
  {
    id: 'call-routing',
    label: 'Call Routing',
    href: '/call-routing',
    group: 'routing',
    icon: Route,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Inbound/outbound routing rules and time-based routing.',
    breadcrumb: ['Call Routing', 'Rules'],
    prismaModels: ['CallPolicy'],
  },
  {
    id: 'ring-groups',
    label: 'Ring Groups',
    href: '/ring-groups',
    group: 'routing',
    icon: PhoneForwarded,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Simultaneous and sequential ring group configuration.',
    breadcrumb: ['Call Routing', 'Ring Groups'],
  },
  {
    id: 'queues',
    label: 'Queues',
    href: '/queues',
    group: 'routing',
    icon: ListOrdered,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Call queue configuration, agents, and strategies.',
    breadcrumb: ['Call Routing', 'Queues'],
    prismaModels: ['Queue', 'QueueMember'],
  },
  {
    id: 'ivr',
    label: 'IVR',
    href: '/ivr',
    group: 'routing',
    icon: Workflow,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Interactive voice response menus and call flows.',
    breadcrumb: ['Call Routing', 'IVR'],
    prismaModels: ['IVR', 'IVRMenu'],
  },
  {
    id: 'voicemail',
    label: 'Voicemail',
    href: '/voicemail',
    group: 'routing',
    icon: Voicemail,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Voicemail boxes, greetings, and notification settings.',
    breadcrumb: ['Call Routing', 'Voicemail'],
    prismaModels: ['Voicemail'],
  },
  {
    id: 'conferences',
    label: 'Conferences',
    href: '/conferences',
    group: 'routing',
    icon: Radio,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Audio conference bridges and participant management.',
    breadcrumb: ['Call Routing', 'Conferences'],
    prismaModels: ['Conference', 'ConferenceParticipant'],
  },

  // ── Analytics ─────────────────────────────────────────────────────
  {
    id: 'cdr',
    label: 'CDR',
    href: '/cdr',
    group: 'analytics',
    icon: FileText,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Call detail records with direction, duration, and disposition.',
    breadcrumb: ['Analytics', 'CDR'],
    prismaModels: ['CallSession', 'CallParticipant'],
  },
  {
    id: 'call-recordings',
    label: 'Recordings',
    href: '/call-recordings',
    group: 'analytics',
    icon: Mic,
    permission: 'recordings:read',
    integration: 'live',
    description: 'Browse and playback call recordings.',
    breadcrumb: ['Analytics', 'Recordings'],
    apiEndpoints: ['/v1/recordings'],
    prismaModels: ['Recording', 'RecordingPolicy'],
  },
  {
    id: 'reports',
    label: 'Reports',
    href: '/reports',
    group: 'analytics',
    icon: Activity,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Usage, quality, and operational reports.',
    breadcrumb: ['Analytics', 'Reports'],
  },

  // ── Billing ───────────────────────────────────────────────────────
  {
    id: 'billing',
    label: 'Billing & Usage',
    href: '/billing',
    group: 'billing',
    icon: CreditCard,
    permission: 'platform:super_admin',
    integration: 'planned',
    description: 'Platform billing, per-tenant usage, and Telnyx cost allocation.',
    breadcrumb: ['Billing', 'Usage'],
  },

  // ── Infrastructure ────────────────────────────────────────────────
  {
    id: 'system-health',
    label: 'System Health',
    href: '/system-health',
    group: 'infrastructure',
    icon: Activity,
    permission: 'platform:super_admin',
    integration: 'bff',
    description: 'Platform readiness, dependency checks, and smoke test status.',
    breadcrumb: ['Infrastructure', 'System Health'],
    apiEndpoints: ['/v1/observability/health/detail', '/v1/production/readiness'],
  },
  {
    id: 'kamailio',
    label: 'Kamailio',
    href: '/kamailio',
    group: 'infrastructure',
    icon: Network,
    permission: 'platform:super_admin',
    integration: 'bff',
    description: 'SIP proxy status, registrations, and persistence.',
    breadcrumb: ['Infrastructure', 'Kamailio'],
    apiEndpoints: ['/v1/ha/kamailio/persistence'],
  },
  {
    id: 'rtpengine',
    label: 'RTPengine',
    href: '/rtpengine',
    group: 'infrastructure',
    icon: AudioLines,
    permission: 'platform:super_admin',
    integration: 'bff',
    description: 'Media engine sessions, ports, and health.',
    breadcrumb: ['Infrastructure', 'RTPengine'],
  },
  {
    id: 'redis',
    label: 'Redis',
    href: '/redis',
    group: 'infrastructure',
    icon: Database,
    permission: 'platform:super_admin',
    integration: 'bff',
    description: 'Redis cluster health and keyspace metrics.',
    breadcrumb: ['Infrastructure', 'Redis'],
  },
  {
    id: 'postgresql',
    label: 'PostgreSQL',
    href: '/postgresql',
    group: 'infrastructure',
    icon: Database,
    permission: 'platform:super_admin',
    integration: 'bff',
    description: 'Database connectivity, replication, and pool status.',
    breadcrumb: ['Infrastructure', 'PostgreSQL'],
  },

  // ── Security & System ─────────────────────────────────────────────
  {
    id: 'audit-logs',
    label: 'Audit Logs',
    href: '/audit-logs',
    group: 'security',
    icon: ShieldCheck,
    permission: 'tenant:admin',
    integration: 'bff',
    description: 'Security and configuration audit trail.',
    breadcrumb: ['Security', 'Audit Logs'],
    apiEndpoints: ['/v1/observability/audit'],
    prismaModels: ['AuditLog'],
  },
  {
    id: 'settings',
    label: 'Settings',
    href: '/settings',
    group: 'system',
    icon: Settings,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Portal preferences, features, and configuration.',
    breadcrumb: ['System', 'Settings'],
    prismaModels: ['TenantSettings', 'TenantFeature'],
  },
];

/** Softphone shortcut — not in sidebar nav */
export const SOFTPHONE_HREF = '/softphone';
export const SOFTPHONE_ICON = Headphones;

export function getModuleByHref(href: string): ModuleDefinition | undefined {
  return MODULES.find((m) => m.href === href);
}

export function getModuleById(id: string): ModuleDefinition | undefined {
  return MODULES.find((m) => m.id === id);
}

export function filterNavByPermissions(permissions: string[]): ModuleDefinition[] {
  return MODULES.filter((item) => hasPermission(permissions, item.permission));
}
