import {
  Activity,
  AudioLines,
  Building2,
  Cable,
  Database,
  FileText,
  GitBranch,
  Headphones,
  KeyRound,
  LayoutDashboard,
  ListOrdered,
  Mic,
  Network,
  Phone,
  PhoneCall,
  PhoneForwarded,
  Radio,
  Route,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  Smartphone,
  Users,
  Voicemail,
  Workflow,
} from 'lucide-react';
import type { ModuleDefinition, NavGroup } from '../../types/navigation';
import { hasPermission } from '../rbac/permissions';

export const NAV_GROUP_LABELS: Record<NavGroup, string> = {
  overview: 'Overview',
  organization: 'Organization',
  telephony: 'Telephony',
  routing: 'Call Routing',
  analytics: 'Analytics',
  operations: 'Operations',
  infrastructure: 'Infrastructure',
  security: 'Security',
  system: 'System',
};

export const MODULES: ModuleDefinition[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    href: '/dashboard',
    group: 'overview',
    icon: LayoutDashboard,
    permission: 'tenant:user',
    integration: 'live',
    description: 'Organization overview, KPIs, and system status at a glance.',
    breadcrumb: ['Dashboard'],
  },
  {
    id: 'organization',
    label: 'Organization',
    href: '/organization',
    group: 'organization',
    icon: Building2,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Tenant profile, sites, and organization settings.',
    breadcrumb: ['Organization', 'Overview'],
    prismaModels: ['Tenant', 'TenantSettings', 'Site'],
  },
  {
    id: 'users',
    label: 'Users',
    href: '/users',
    group: 'organization',
    icon: Users,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Manage user accounts, profiles, and site assignments.',
    breadcrumb: ['Organization', 'Users'],
    prismaModels: ['User', 'UserProfile', 'UserSite'],
  },
  {
    id: 'roles',
    label: 'Roles',
    href: '/roles',
    group: 'organization',
    icon: Shield,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Define roles and assign permissions to user groups.',
    breadcrumb: ['Organization', 'Roles'],
    prismaModels: ['Role', 'UserRole'],
  },
  {
    id: 'permissions',
    label: 'Permissions',
    href: '/permissions',
    group: 'organization',
    icon: KeyRound,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'View and manage the permission catalog for your tenant.',
    breadcrumb: ['Organization', 'Permissions'],
    prismaModels: ['Permission', 'RolePermission'],
  },
  {
    id: 'extensions',
    label: 'Extensions',
    href: '/extensions',
    group: 'telephony',
    icon: Phone,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Extension numbers, line assignments, and dial plans.',
    breadcrumb: ['Telephony', 'Extensions'],
    prismaModels: ['Extension', 'Line'],
  },
  {
    id: 'devices',
    label: 'Devices',
    href: '/devices',
    group: 'telephony',
    icon: Smartphone,
    permission: 'provisioning:admin',
    integration: 'live',
    description: 'Desk phones, softphones, and device enrollment.',
    breadcrumb: ['Telephony', 'Devices'],
    apiEndpoints: ['/v1/provisioning/devices/enroll'],
    prismaModels: ['Device', 'DeviceAssignment'],
  },
  {
    id: 'sip-accounts',
    label: 'SIP Accounts',
    href: '/sip-accounts',
    group: 'telephony',
    icon: Network,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'SIP endpoint credentials and registration profiles.',
    breadcrumb: ['Telephony', 'SIP Accounts'],
    prismaModels: ['SIPEndpoint'],
  },
  {
    id: 'dids',
    label: 'DIDs',
    href: '/dids',
    group: 'telephony',
    icon: PhoneCall,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Direct inward dialing numbers and assignments.',
    breadcrumb: ['Telephony', 'DIDs'],
    prismaModels: ['PhoneNumber', 'NumberAssignment'],
  },
  {
    id: 'trunks',
    label: 'Trunks',
    href: '/trunks',
    group: 'telephony',
    icon: Cable,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'SIP trunks and carrier interconnect configuration.',
    breadcrumb: ['Telephony', 'Trunks'],
    prismaModels: ['Carrier'],
  },
  {
    id: 'call-routing',
    label: 'Call Routing',
    href: '/call-routing',
    group: 'routing',
    icon: Route,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Inbound/outbound routing rules and time-based routing.',
    breadcrumb: ['Call Routing', 'Rules'],
    prismaModels: ['CallPolicy'],
  },
  {
    id: 'ring-groups',
    label: 'Ring Groups',
    href: '/ring-groups',
    group: 'routing',
    icon: PhoneForwarded,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Simultaneous and sequential ring group configuration.',
    breadcrumb: ['Call Routing', 'Ring Groups'],
  },
  {
    id: 'queues',
    label: 'Queues',
    href: '/queues',
    group: 'routing',
    icon: ListOrdered,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Call queue configuration, agents, and strategies.',
    breadcrumb: ['Call Routing', 'Queues'],
    prismaModels: ['Queue', 'QueueMember'],
  },
  {
    id: 'ivr',
    label: 'IVR',
    href: '/ivr',
    group: 'routing',
    icon: Workflow,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Interactive voice response menus and call flows.',
    breadcrumb: ['Call Routing', 'IVR'],
    prismaModels: ['IVR', 'IVRMenu'],
  },
  {
    id: 'voicemail',
    label: 'Voicemail',
    href: '/voicemail',
    group: 'routing',
    icon: Voicemail,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Voicemail boxes, greetings, and notification settings.',
    breadcrumb: ['Call Routing', 'Voicemail'],
    prismaModels: ['Voicemail'],
  },
  {
    id: 'conferences',
    label: 'Conferences',
    href: '/conferences',
    group: 'routing',
    icon: Radio,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Audio conference bridges and participant management.',
    breadcrumb: ['Call Routing', 'Conferences'],
    prismaModels: ['Conference', 'ConferenceParticipant'],
  },
  {
    id: 'call-recordings',
    label: 'Call Recordings',
    href: '/call-recordings',
    group: 'analytics',
    icon: Mic,
    permission: 'recordings:read',
    integration: 'live',
    description: 'Browse and playback call recordings.',
    breadcrumb: ['Analytics', 'Call Recordings'],
    apiEndpoints: ['/v1/recordings'],
    prismaModels: ['Recording', 'RecordingPolicy'],
  },
  {
    id: 'cdr',
    label: 'CDR',
    href: '/cdr',
    group: 'analytics',
    icon: FileText,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Call detail records and billing export.',
    breadcrumb: ['Analytics', 'CDR'],
    prismaModels: ['CallSession', 'CallParticipant'],
  },
  {
    id: 'reports',
    label: 'Reports',
    href: '/reports',
    group: 'analytics',
    icon: Activity,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Operational and usage reports across your organization.',
    breadcrumb: ['Analytics', 'Reports'],
  },
  {
    id: 'provisioning',
    label: 'Provisioning',
    href: '/provisioning',
    group: 'operations',
    icon: Server,
    permission: 'provisioning:admin',
    integration: 'live',
    description: 'Device provisioning workflows and firmware management.',
    breadcrumb: ['Operations', 'Provisioning'],
    apiEndpoints: ['/v1/provisioning/devices/*'],
  },
  {
    id: 'carriers',
    label: 'Carriers',
    href: '/carriers',
    group: 'operations',
    icon: GitBranch,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Carrier integrations and PSTN connectivity.',
    breadcrumb: ['Operations', 'Carriers'],
    prismaModels: ['Carrier'],
  },
  {
    id: 'kamailio',
    label: 'Kamailio',
    href: '/kamailio',
    group: 'infrastructure',
    icon: Network,
    permission: 'platform:super_admin',
    integration: 'bff',
    description: 'SIP proxy status, registrations, and persistence.',
    breadcrumb: ['Infrastructure', 'Kamailio'],
    apiEndpoints: ['/v1/ha/kamailio/persistence'],
  },
  {
    id: 'rtpengine',
    label: 'RTPengine',
    href: '/rtpengine',
    group: 'infrastructure',
    icon: AudioLines,
    permission: 'platform:super_admin',
    integration: 'bff',
    description: 'Media engine sessions, ports, and health.',
    breadcrumb: ['Infrastructure', 'RTPengine'],
  },
  {
    id: 'redis',
    label: 'Redis',
    href: '/redis',
    group: 'infrastructure',
    icon: Database,
    permission: 'platform:super_admin',
    integration: 'bff',
    description: 'Redis cluster health, persistence, and keyspace metrics.',
    breadcrumb: ['Infrastructure', 'Redis'],
  },
  {
    id: 'postgresql',
    label: 'PostgreSQL',
    href: '/postgresql',
    group: 'infrastructure',
    icon: Database,
    permission: 'platform:super_admin',
    integration: 'bff',
    description: 'Database connectivity, replication, and pool status.',
    breadcrumb: ['Infrastructure', 'PostgreSQL'],
  },
  {
    id: 'system-health',
    label: 'System Health',
    href: '/system-health',
    group: 'infrastructure',
    icon: Activity,
    permission: 'platform:super_admin',
    integration: 'bff',
    description: 'Platform readiness, dependency checks, and smoke test status.',
    breadcrumb: ['Infrastructure', 'System Health'],
    apiEndpoints: ['/v1/observability/dashboard', '/v1/production/readiness'],
  },
  {
    id: 'audit-logs',
    label: 'Audit Logs',
    href: '/audit-logs',
    group: 'security',
    icon: ShieldCheck,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Security and configuration audit trail.',
    breadcrumb: ['Security', 'Audit Logs'],
    prismaModels: ['AuditLog'],
  },
  {
    id: 'settings',
    label: 'Settings',
    href: '/settings',
    group: 'system',
    icon: Settings,
    permission: 'tenant:admin',
    integration: 'planned',
    description: 'Tenant preferences, features, and portal configuration.',
    breadcrumb: ['System', 'Settings'],
    prismaModels: ['TenantSettings', 'TenantFeature'],
  },
];

export function getModuleByHref(href: string): ModuleDefinition | undefined {
  return MODULES.find((m) => m.href === href);
}

export function getModuleById(id: string): ModuleDefinition | undefined {
  return MODULES.find((m) => m.id === id);
}

export function filterNavByPermissions(permissions: string[]): ModuleDefinition[] {
  return MODULES.filter((item) => hasPermission(permissions, item.permission));
}
