import {
  Activity,
  AudioLines,
  Cable,
  Database,
  GitBranch,
  Headphones,
  LayoutDashboard,
  Network,
  PhoneIncoming,
  ShieldCheck,
} from 'lucide-react';
import type { ModuleDefinition } from '../../types/navigation';
import { PERMISSIONS } from '../rbac/permissions';

export const OPS_MODULES: ModuleDefinition[] = [
  {
    id: 'dashboard',
    label: 'Operations Dashboard',
    href: '/dashboard',
    group: 'operations',
    icon: LayoutDashboard,
    permission: PERMISSIONS.OPS_DASHBOARD_READ,
    integration: 'live',
    description: 'Live PBX operations — calls, registrations, tenants, and carrier health.',
    breadcrumb: ['Operations Center', 'Dashboard'],
    apiEndpoints: ['/v1/ops/dashboard'],
  },
  {
    id: 'supervisor',
    label: 'Supervisor Console',
    href: '/supervisor',
    group: 'operations',
    icon: Headphones,
    permission: PERMISSIONS.SUPERVISOR_DASHBOARD_READ,
    integration: 'live',
    description: 'Contact center supervisor dashboard, agent monitoring, queue control, and live call supervision.',
    breadcrumb: ['Operations Center', 'Supervisor Console'],
    apiEndpoints: ['/v1/supervisor/dashboard', '/v1/supervisor/agents', '/v1/supervisor/calls/live'],
  },
  {
    id: 'live-calls',
    label: 'Live Calls',
    href: '/live-calls',
    group: 'operations',
    icon: PhoneIncoming,
    permission: PERMISSIONS.OPS_LIVE_CALLS_READ,
    integration: 'live',
    description: 'Real-time active call sessions across the platform.',
    breadcrumb: ['Operations Center', 'Live Calls'],
    apiEndpoints: ['/v1/live-calls'],
  },
  {
    id: 'system-health',
    label: 'System Health',
    href: '/system-health',
    group: 'infrastructure',
    icon: Activity,
    permission: PERMISSIONS.OPS_HEALTH_READ,
    integration: 'live',
    description: 'Platform readiness, dependency checks, and deployment status.',
    breadcrumb: ['Infrastructure', 'System Health'],
    apiEndpoints: ['/v1/ops/health'],
  },
  {
    id: 'kamailio',
    label: 'Kamailio',
    href: '/kamailio',
    group: 'infrastructure',
    icon: Network,
    permission: PERMISSIONS.OPS_INFRA_READ,
    integration: 'live',
    description: 'SIP proxy status, registrations, and persistence.',
    breadcrumb: ['Infrastructure', 'Kamailio'],
    apiEndpoints: ['/v1/ops/kamailio/persistence'],
  },
  {
    id: 'rtpengine',
    label: 'RTPengine',
    href: '/rtpengine',
    group: 'infrastructure',
    icon: AudioLines,
    permission: PERMISSIONS.OPS_INFRA_READ,
    integration: 'live',
    description: 'Media engine sessions, ports, and health.',
    breadcrumb: ['Infrastructure', 'RTPengine'],
    apiEndpoints: ['/v1/ops/rtpengine/nodes'],
  },
  {
    id: 'redis',
    label: 'Redis',
    href: '/redis',
    group: 'infrastructure',
    icon: Database,
    permission: PERMISSIONS.OPS_HEALTH_READ,
    integration: 'live',
    description: 'Redis cluster health and keyspace metrics.',
    breadcrumb: ['Infrastructure', 'Redis'],
    apiEndpoints: ['/v1/ops/redis/stats'],
  },
  {
    id: 'postgresql',
    label: 'PostgreSQL',
    href: '/postgresql',
    group: 'infrastructure',
    icon: Database,
    permission: PERMISSIONS.OPS_HEALTH_READ,
    integration: 'live',
    description: 'Database connectivity, replication, and pool status.',
    breadcrumb: ['Infrastructure', 'PostgreSQL'],
    apiEndpoints: ['/v1/ops/postgres/stats'],
  },
  {
    id: 'trunks',
    label: 'SIP Trunks',
    href: '/trunks',
    group: 'carrier',
    icon: Cable,
    permission: PERMISSIONS.OPS_HEALTH_READ,
    integration: 'live',
    description: 'SIP trunks, channel capacity, failover, and registration status.',
    breadcrumb: ['Carrier & Numbers', 'SIP Trunks'],
    apiEndpoints: ['/v1/carriers/trunks'],
  },
  {
    id: 'sip-accounts',
    label: 'SIP Registrations',
    href: '/sip-accounts',
    group: 'telephony',
    icon: Network,
    permission: PERMISSIONS.OPS_INFRA_READ,
    integration: 'live',
    description: 'SIP endpoint credentials and live registration status.',
    breadcrumb: ['PBX', 'SIP Registrations'],
    apiEndpoints: ['/v1/ops/sip/registrations'],
  },
  {
    id: 'carriers',
    label: 'Carrier Health',
    href: '/carriers',
    group: 'carrier',
    icon: GitBranch,
    permission: PERMISSIONS.OPS_HEALTH_READ,
    integration: 'live',
    description: 'Carrier adapter health and PSTN interconnect status.',
    breadcrumb: ['Carrier & Numbers', 'Health'],
    apiEndpoints: ['/v1/ops/carriers/health'],
  },
  {
    id: 'audit-logs',
    label: 'Audit Logs',
    href: '/audit-logs',
    group: 'security',
    icon: ShieldCheck,
    permission: PERMISSIONS.OPS_TRACE_READ,
    integration: 'live',
    description: 'Operations audit trail and trace events.',
    breadcrumb: ['Security', 'Audit Logs'],
    apiEndpoints: ['/v1/ops/audit'],
  },
];
