import {
  Building2,
  CreditCard,
  GitBranch,
  KeyRound,
  LayoutDashboard,
  PhoneCall,
  Settings,
  Shield,
  ShieldCheck,
} from 'lucide-react';
import type { ModuleDefinition } from '../../types/navigation';
import { PERMISSIONS } from '../rbac/permissions';

export const PLATFORM_MODULES: ModuleDefinition[] = [
  {
    id: 'dashboard',
    label: 'Platform Dashboard',
    href: '/dashboard',
    group: 'operations',
    icon: LayoutDashboard,
    permission: PERMISSIONS.PLATFORM_DASHBOARD_READ,
    integration: 'live',
    description: 'Platform-wide KPIs — tenants, revenue, carrier inventory, and alerts.',
    breadcrumb: ['Platform', 'Dashboard'],
    apiEndpoints: ['/v1/platform/dashboard'],
  },
  {
    id: 'tenants',
    label: 'Tenants',
    href: '/tenants',
    group: 'platform',
    icon: Building2,
    permission: PERMISSIONS.PLATFORM_TENANTS_READ,
    integration: 'live',
    description: 'Multi-tenant organizations, lifecycle, and administration.',
    breadcrumb: ['Platform', 'Tenants'],
    apiEndpoints: ['/v1/platform/tenants'],
  },
  {
    id: 'billing',
    label: 'Billing & Usage',
    href: '/billing',
    group: 'billing',
    icon: CreditCard,
    permission: PERMISSIONS.PLATFORM_BILLING_READ,
    integration: 'live',
    description: 'Platform billing, subscriptions, and carrier cost allocation.',
    breadcrumb: ['Billing', 'Usage'],
    apiEndpoints: ['/v1/platform/billing/summary'],
  },
  {
    id: 'telnyx-numbers',
    label: 'Telnyx Numbers',
    href: '/telnyx-numbers',
    group: 'carrier',
    icon: PhoneCall,
    permission: PERMISSIONS.PLATFORM_TELNYX_READ,
    integration: 'live',
    primary: true,
    description: 'Platform-wide Telnyx phone number inventory.',
    breadcrumb: ['Carrier & Numbers', 'Telnyx Numbers'],
    apiEndpoints: ['/v1/carriers/telnyx/numbers'],
  },
  {
    id: 'carriers',
    label: 'Carrier Integrations',
    href: '/carriers',
    group: 'carrier',
    icon: GitBranch,
    permission: PERMISSIONS.PLATFORM_CARRIERS_READ,
    integration: 'live',
    description: 'Carrier adapters, health status, and interconnect configuration.',
    breadcrumb: ['Carrier & Numbers', 'Integrations'],
    apiEndpoints: ['/v1/platform/carriers'],
  },
  {
    id: 'roles',
    label: 'Roles',
    href: '/roles',
    group: 'platform',
    icon: Shield,
    permission: PERMISSIONS.PLATFORM_ROLES_READ,
    integration: 'live',
    description: 'Role definitions and permission assignments across tenants.',
    breadcrumb: ['Platform', 'Roles'],
    apiEndpoints: ['/v1/platform/roles'],
  },
  {
    id: 'permissions',
    label: 'Permissions',
    href: '/permissions',
    group: 'platform',
    icon: KeyRound,
    permission: PERMISSIONS.PLATFORM_ROLES_READ,
    integration: 'live',
    description: 'Permission catalog for RBAC configuration.',
    breadcrumb: ['Platform', 'Permissions'],
    apiEndpoints: ['/v1/platform/permissions'],
  },
  {
    id: 'audit-logs',
    label: 'Audit Logs',
    href: '/audit-logs',
    group: 'security',
    icon: ShieldCheck,
    permission: PERMISSIONS.PLATFORM_AUDIT_READ,
    integration: 'live',
    description: 'Platform security and configuration audit trail.',
    breadcrumb: ['Security', 'Audit Logs'],
    apiEndpoints: ['/v1/platform/audit'],
  },
  {
    id: 'settings',
    label: 'Settings',
    href: '/settings',
    group: 'system',
    icon: Settings,
    permission: PERMISSIONS.PLATFORM_SETTINGS_READ,
    integration: 'live',
    description: 'Platform preferences, features, and configuration.',
    breadcrumb: ['System', 'Settings'],
  },
];
