import {
  Activity,
  BarChart3,
  Building2,
  Cable,
  ClipboardList,
  CreditCard,
  GitBranch,
  Key,
  KeyRound,
  Landmark,
  LayoutDashboard,
  PhoneCall,
  Router,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Terminal,
  Users,
} from 'lucide-react';
import type { ModuleDefinition } from '../../types/navigation';
import { PERMISSIONS } from '../rbac/permissions';

export const PLATFORM_MODULES: ModuleDefinition[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    href: '/dashboard',
    group: 'platform',
    icon: LayoutDashboard,
    permission: PERMISSIONS.PLATFORM_DASHBOARD_READ,
    integration: 'live',
    description: 'Platform-wide KPIs — tenants, revenue, carrier inventory, and alerts.',
    breadcrumb: ['Platform', 'Dashboard'],
    apiEndpoints: ['/v1/platform/dashboard'],
  },
  {
    id: 'tenants',
    label: 'Tenants',
    href: '/tenants',
    group: 'platform',
    icon: Building2,
    permission: PERMISSIONS.PLATFORM_TENANTS_READ,
    integration: 'live',
    description: 'Multi-tenant organizations, lifecycle, and administration.',
    breadcrumb: ['Platform', 'Tenants'],
    apiEndpoints: ['/v1/platform/tenants', '/v1/platform/tenants/onboard'],
  },
  {
    id: 'organization',
    label: 'Company Profile',
    href: '/organization',
    group: 'platform',
    icon: Landmark,
    permission: PERMISSIONS.PLATFORM_TENANTS_READ,
    integration: 'live',
    description: 'Company profile — branding, contact, timezone, and business hours.',
    breadcrumb: ['Platform', 'Company Profile'],
    apiEndpoints: ['/v1/platform/organization'],
  },
  {
    id: 'developer-tools',
    label: 'Developer Tools',
    href: '/developer-tools',
    group: 'platform',
    icon: Terminal,
    permission: PERMISSIONS.PLATFORM_DEVTOOLS,
    requiresDeveloperMode: true,
    integration: 'live',
    description: 'Reset Tenant, demo seed, and pilot developer utilities (Developer Mode).',
    breadcrumb: ['Platform', 'Developer Tools'],
    apiEndpoints: ['/v1/platform/dev-tools'],
  },
  {
    id: 'users',
    label: 'Users',
    href: '/users',
    group: 'platform',
    icon: Users,
    permission: PERMISSIONS.PLATFORM_TENANTS_READ,
    integration: 'live',
    description: 'User accounts across tenant organizations.',
    breadcrumb: ['Platform', 'Users'],
    apiEndpoints: ['/v1/platform/users'],
  },
  {
    id: 'roles',
    label: 'Roles',
    href: '/roles',
    group: 'platform',
    icon: Shield,
    permission: PERMISSIONS.PLATFORM_ROLES_READ,
    integration: 'live',
    description: 'Role definitions and permission assignments across tenants.',
    breadcrumb: ['Platform', 'Roles'],
    apiEndpoints: ['/v1/platform/roles'],
  },
  {
    id: 'permissions',
    label: 'Permissions',
    href: '/permissions',
    group: 'platform',
    icon: KeyRound,
    permission: PERMISSIONS.PLATFORM_ROLES_READ,
    integration: 'live',
    description: 'Permission catalog for RBAC configuration.',
    breadcrumb: ['Platform', 'Permissions'],
    apiEndpoints: ['/v1/platform/permissions'],
  },
  {
    id: 'api-keys',
    label: 'API Keys',
    href: '/api-keys',
    group: 'platform',
    icon: Key,
    permission: PERMISSIONS.PLATFORM_API_KEYS_READ,
    integration: 'live',
    description: 'Platform and tenant API key management.',
    breadcrumb: ['Platform', 'API Keys'],
    apiEndpoints: ['/v1/platform/api-keys'],
  },
  {
    id: 'settings',
    label: 'Settings',
    href: '/settings',
    group: 'platform',
    icon: Settings,
    permission: PERMISSIONS.PLATFORM_SETTINGS_READ,
    integration: 'live',
    description: 'Platform preferences, SMTP, and configuration.',
    breadcrumb: ['Platform', 'Settings'],
    apiEndpoints: ['/v1/platform/settings'],
  },
  {
    id: 'provisioning-settings',
    label: 'Provisioning Settings',
    href: '/provisioning-settings',
    group: 'platform',
    icon: Router,
    permission: PERMISSIONS.PLATFORM_SETTINGS_READ,
    integration: 'live',
    description: 'Provision server base URL, supported vendors, service status, and templates.',
    breadcrumb: ['Platform', 'Provisioning Settings'],
    apiEndpoints: ['/v1/platform/provisioning/settings'],
  },
  {
    id: 'telnyx-numbers',
    label: 'Telnyx Numbers',
    href: '/telnyx-numbers',
    group: 'carrier',
    icon: PhoneCall,
    permission: PERMISSIONS.PLATFORM_TELNYX_READ,
    integration: 'live',
    primary: true,
    description: 'Platform-wide Telnyx phone number inventory and Mission Control.',
    breadcrumb: ['Carrier & Numbers', 'Telnyx Numbers'],
    apiEndpoints: ['/v1/carriers/telnyx/numbers', '/v1/carriers/telnyx/numbers/dashboard'],
  },
  {
    id: 'number-marketplace',
    label: 'Number Marketplace',
    href: '/number-marketplace',
    group: 'carrier',
    icon: ShoppingCart,
    permission: PERMISSIONS.PLATFORM_TELNYX_READ,
    integration: 'live',
    description: 'Search available numbers and purchase into platform inventory.',
    breadcrumb: ['Carrier & Numbers', 'Number Marketplace'],
    apiEndpoints: ['/v1/carriers/telnyx/numbers/search/available', '/v1/carriers/telnyx/numbers/purchase'],
  },
  {
    id: 'number-requests',
    label: 'Number Requests',
    href: '/number-requests',
    group: 'carrier',
    icon: ClipboardList,
    permission: PERMISSIONS.PLATFORM_TELNYX_READ,
    integration: 'live',
    description: 'Review and approve tenant number reservation and assignment requests.',
    breadcrumb: ['Carrier & Numbers', 'Number Requests'],
    apiEndpoints: ['/v1/carriers/telnyx/numbers/requests'],
  },
  {
    id: 'carriers',
    label: 'Carrier Integrations',
    href: '/carriers',
    group: 'carrier',
    icon: GitBranch,
    permission: PERMISSIONS.PLATFORM_CARRIERS_READ,
    integration: 'live',
    description: 'Carrier adapters, health status, and interconnect configuration.',
    breadcrumb: ['Carrier & Numbers', 'Carrier Integrations'],
    apiEndpoints: ['/v1/platform/carriers'],
  },
  {
    id: 'trunks',
    label: 'SIP Trunks',
    href: '/trunks',
    group: 'carrier',
    icon: Cable,
    permission: PERMISSIONS.PLATFORM_CARRIERS_READ,
    integration: 'live',
    description: 'SIP trunks, channel capacity, failover, and registration status.',
    breadcrumb: ['Carrier & Numbers', 'SIP Trunks'],
    apiEndpoints: ['/v1/carriers/trunks'],
  },
  {
    id: 'billing',
    label: 'Billing Dashboard',
    href: '/billing',
    group: 'billing',
    icon: CreditCard,
    permission: PERMISSIONS.PLATFORM_BILLING_READ,
    integration: 'live',
    description: 'Platform billing summary — MRR, carrier cost, subscriptions, and invoices.',
    breadcrumb: ['Billing', 'Dashboard'],
    apiEndpoints: [
      '/v1/platform/billing/summary',
      '/v1/platform/billing/plans',
      '/v1/platform/billing/subscriptions',
      '/v1/platform/billing/invoices',
    ],
  },
  {
    id: 'audit-logs',
    label: 'Audit Logs',
    href: '/audit-logs',
    group: 'reports',
    icon: ShieldCheck,
    permission: PERMISSIONS.PLATFORM_AUDIT_READ,
    integration: 'live',
    description: 'Platform security and configuration audit trail.',
    breadcrumb: ['Reports', 'Audit Logs'],
    apiEndpoints: ['/v1/platform/audit'],
  },
  {
    id: 'marketplace-reports',
    label: 'Marketplace Reports',
    href: '/marketplace-reports',
    group: 'reports',
    icon: BarChart3,
    permission: PERMISSIONS.PLATFORM_TELNYX_READ,
    integration: 'live',
    description: 'Number marketplace KPIs — requests, reservations, and approval metrics.',
    breadcrumb: ['Reports', 'Marketplace Reports'],
    apiEndpoints: ['/v1/carriers/telnyx/numbers/reports/marketplace'],
  },
  {
    id: 'system-health',
    label: 'System Health',
    href: '/system-health',
    group: 'infrastructure',
    icon: Activity,
    permission: PERMISSIONS.OPS_HEALTH_READ,
    integration: 'live',
    description: 'Platform readiness, dependency checks, and deployment status.',
    breadcrumb: ['Infrastructure', 'System Health'],
    apiEndpoints: ['/v1/ops/health'],
  },
];
