import {
  Activity,
  Building2,
  FileText,
  Headphones,
  LayoutDashboard,
  ListOrdered,
  Megaphone,
  Mic,
  Network,
  Phone,
  PhoneForwarded,
  Radio,
  Route,
  Server,
  Settings,
  Smartphone,
  Users,
  Voicemail,
  Volume2,
  Workflow,
} from 'lucide-react';
import type { ModuleDefinition } from '../../types/navigation';
import { PERMISSIONS } from '../rbac/permissions';

export const TENANT_MODULES: ModuleDefinition[] = [
  {
    id: 'dashboard',
    label: 'Tenant Dashboard',
    href: '/dashboard',
    group: 'operations',
    icon: LayoutDashboard,
    permission: PERMISSIONS.TENANT_DASHBOARD_READ,
    integration: 'live',
    description: 'Tenant operations snapshot — calls, extensions, and devices.',
    breadcrumb: ['Tenant', 'Dashboard'],
    apiEndpoints: ['/v1/tenant/dashboard'],
  },
  {
    id: 'supervisor',
    label: 'Supervisor Console',
    href: '/supervisor',
    group: 'operations',
    icon: Headphones,
    permission: PERMISSIONS.SUPERVISOR_DASHBOARD_READ,
    integration: 'live',
    description: 'Real-time contact center supervision — agents, queues, SLAs, live calls, recordings, and coaching.',
    breadcrumb: ['Contact Center', 'Supervisor Console'],
    apiEndpoints: ['/v1/supervisor/dashboard', '/v1/supervisor/wallboard', '/v1/supervisor/agents'],
  },
  {
    id: 'reception',
    label: 'Reception Console',
    href: '/reception',
    group: 'operations',
    icon: PhoneForwarded,
    permission: PERMISSIONS.TENANT_RECEPTION_READ,
    integration: 'live',
    description: 'Enterprise operator console — directory, BLF, park, pickup, transfers, and live call control.',
    breadcrumb: ['Operations', 'Reception Console'],
    apiEndpoints: ['/v1/tenant/reception', '/v1/tenant/contacts', '/v1/tenant/blf', '/v1/tenant/presence'],
  },
  {
    id: 'paging-intercom',
    label: 'Paging & Intercom',
    href: '/paging-intercom',
    group: 'operations',
    icon: Megaphone,
    permission: PERMISSIONS.TENANT_PAGING_READ,
    integration: 'live',
    description: 'Multicast/SIP paging, zone paging, emergency broadcast, and intercom endpoints.',
    breadcrumb: ['Operations', 'Paging & Intercom'],
    apiEndpoints: ['/v1/tenant/paging'],
  },
  {
    id: 'organization',
    label: 'Organization',
    href: '/organization',
    group: 'platform',
    icon: Building2,
    permission: PERMISSIONS.TENANT_SETTINGS_READ,
    integration: 'live',
    description: 'Current tenant profile, sites, and organization settings.',
    breadcrumb: ['Platform', 'Organization'],
  },
  {
    id: 'users',
    label: 'Users',
    href: '/users',
    group: 'platform',
    icon: Users,
    permission: PERMISSIONS.TENANT_USERS_READ,
    integration: 'live',
    description: 'User accounts, profiles, and site assignments.',
    breadcrumb: ['Platform', 'Users'],
    apiEndpoints: ['/v1/tenant/users'],
  },
  {
    id: 'extensions',
    label: 'Extensions',
    href: '/extensions',
    group: 'telephony',
    icon: Phone,
    permission: PERMISSIONS.TENANT_EXTENSIONS_READ,
    integration: 'live',
    description: 'Extension numbers, line assignments, and dial plans.',
    breadcrumb: ['PBX', 'Extensions'],
    apiEndpoints: ['/v1/tenant/extensions'],
  },
  {
    id: 'devices',
    label: 'Devices',
    href: '/devices',
    group: 'telephony',
    icon: Smartphone,
    permission: PERMISSIONS.TENANT_DEVICES_READ,
    integration: 'live',
    description: 'Desk phones, registrations, firmware, and MAC inventory.',
    breadcrumb: ['PBX', 'Devices'],
    apiEndpoints: ['/v1/tenant/devices', '/v1/tenant/provisioning'],
  },
  {
    id: 'sip-accounts',
    label: 'SIP Registrations',
    href: '/sip-accounts',
    group: 'telephony',
    icon: Network,
    permission: PERMISSIONS.TENANT_DEVICES_READ,
    integration: 'live',
    description: 'SIP endpoint credentials and live registration status.',
    breadcrumb: ['PBX', 'SIP Registrations'],
    apiEndpoints: ['/v1/tenant/devices', '/v1/tenant/provisioning'],
  },
  {
    id: 'provisioning',
    label: 'Provisioning',
    href: '/provisioning',
    group: 'telephony',
    icon: Server,
    permission: PERMISSIONS.PROVISIONING_ADMIN,
    integration: 'live',
    description: 'Zero-touch provisioning, templates, and firmware rollout.',
    breadcrumb: ['PBX', 'Provisioning'],
    apiEndpoints: ['/v1/tenant/provisioning'],
  },
  {
    id: 'dids',
    label: 'Number Marketplace',
    href: '/dids',
    group: 'carrier',
    icon: Phone,
    permission: PERMISSIONS.TENANT_DIDS_READ,
    integration: 'live',
    description: 'Browse platform inventory, reserve numbers, submit requests, and manage assigned DIDs.',
    breadcrumb: ['Carrier & Numbers', 'Marketplace'],
    apiEndpoints: ['/v1/tenant/marketplace', '/v1/tenant/number-requests', '/v1/tenant/dids'],
  },
  {
    id: 'call-routing',
    label: 'Call Routing',
    href: '/call-routing',
    group: 'routing',
    icon: Route,
    permission: PERMISSIONS.TENANT_ROUTING_READ,
    integration: 'live',
    description: 'Inbound/outbound routing rules, dial plans, time conditions, and holidays.',
    breadcrumb: ['Call Routing', 'Rules'],
    apiEndpoints: [
      '/v1/tenant/routing/policies',
      '/v1/tenant/routing/inbound',
      '/v1/tenant/routing/outbound',
      '/v1/tenant/dial-plans',
      '/v1/tenant/time-conditions',
      '/v1/tenant/holiday-calendars',
    ],
  },
  {
    id: 'ring-groups',
    label: 'Ring Groups',
    href: '/ring-groups',
    group: 'routing',
    icon: PhoneForwarded,
    permission: PERMISSIONS.TENANT_ROUTING_READ,
    integration: 'live',
    description: 'Simultaneous and sequential ring group configuration.',
    breadcrumb: ['Call Routing', 'Ring Groups'],
    apiEndpoints: ['/v1/tenant/ring-groups'],
  },
  {
    id: 'queues',
    label: 'Queues',
    href: '/queues',
    group: 'routing',
    icon: ListOrdered,
    permission: PERMISSIONS.TENANT_QUEUES_READ,
    integration: 'live',
    description: 'Call queue configuration, agents, and strategies.',
    breadcrumb: ['Call Routing', 'Queues'],
    apiEndpoints: ['/v1/tenant/queues'],
  },
  {
    id: 'audio-library',
    label: 'Audio Library',
    href: '/audio-library',
    group: 'routing',
    icon: Volume2,
    permission: PERMISSIONS.TENANT_IVR_READ,
    integration: 'live',
    description: 'Music on hold playlists, announcements, prompts, and audio versioning.',
    breadcrumb: ['Call Routing', 'Audio Library'],
    apiEndpoints: ['/v1/tenant/audio'],
  },
  {
    id: 'ivr',
    label: 'IVR',
    href: '/ivr',
    group: 'routing',
    icon: Workflow,
    permission: PERMISSIONS.TENANT_IVR_READ,
    integration: 'live',
    description: 'Interactive voice response menus and call flows.',
    breadcrumb: ['Call Routing', 'IVR'],
    apiEndpoints: ['/v1/tenant/ivrs', '/v1/tenant/audio/announcements'],
  },
  {
    id: 'voicemail',
    label: 'Voicemail',
    href: '/voicemail',
    group: 'routing',
    icon: Voicemail,
    permission: PERMISSIONS.TENANT_VOICEMAIL_READ,
    integration: 'live',
    description: 'Voicemail boxes, greetings, and notification settings.',
    breadcrumb: ['Call Routing', 'Voicemail'],
    apiEndpoints: ['/v1/tenant/voicemail'],
  },
  {
    id: 'conferences',
    label: 'Conferences',
    href: '/conferences',
    group: 'routing',
    icon: Radio,
    permission: PERMISSIONS.TENANT_CONFERENCES_READ,
    integration: 'live',
    description: 'Audio conference bridges and participant management.',
    breadcrumb: ['Call Routing', 'Conferences'],
    apiEndpoints: ['/v1/tenant/conferences'],
  },
  {
    id: 'cdr',
    label: 'CDR',
    href: '/cdr',
    group: 'analytics',
    icon: FileText,
    permission: PERMISSIONS.TENANT_CDR_READ,
    integration: 'live',
    description: 'Call detail records with direction, duration, and disposition.',
    breadcrumb: ['Analytics', 'CDR'],
    apiEndpoints: ['/v1/tenant/cdr'],
  },
  {
    id: 'call-recordings',
    label: 'Recordings',
    href: '/call-recordings',
    group: 'analytics',
    icon: Mic,
    permission: PERMISSIONS.RECORDINGS_READ,
    integration: 'live',
    description: 'Browse and playback call recordings.',
    breadcrumb: ['Analytics', 'Recordings'],
    apiEndpoints: ['/v1/tenant/recordings', '/v1/tenant/recording-policies'],
  },
  {
    id: 'reports',
    label: 'Reports',
    href: '/reports',
    group: 'analytics',
    icon: Activity,
    permission: PERMISSIONS.TENANT_REPORTS_READ,
    integration: 'live',
    description: 'Usage, quality, and operational reports.',
    breadcrumb: ['Analytics', 'Reports'],
    apiEndpoints: ['/v1/tenant/cdr'],
  },
  {
    id: 'settings',
    label: 'Settings',
    href: '/settings',
    group: 'system',
    icon: Settings,
    permission: PERMISSIONS.TENANT_SETTINGS_READ,
    integration: 'live',
    description: 'Portal preferences, features, and configuration.',
    breadcrumb: ['System', 'Settings'],
  },
];
