import {
  Activity,
  Building2,
  Calendar,
  Clock,
  FileText,
  Headphones,
  Key,
  LayoutDashboard,
  ListOrdered,
  Megaphone,
  Mic,
  Network,
  Phone,
  PhoneForwarded,
  Radio,
  Route,
  Settings,
  Shield,
  Smartphone,
  Users,
  Voicemail,
  Volume2,
  Workflow,
} from 'lucide-react';
import type { ModuleDefinition } from '../../types/navigation';
import type { TenantNavSection } from '../../types/navigation';
import { PERMISSIONS } from '../rbac/permissions';

/** Flat tenant module list for Tenant Portal V2 (workflow-first navigation). */
export const TENANT_MODULES_V2: ModuleDefinition[] = [
  {
    id: 'extensions',
    label: 'Extensions',
    href: '/extensions',
    group: 'telephony',
    section: 'dashboard',
    icon: Phone,
    permission: PERMISSIONS.TENANT_EXTENSIONS_READ,
    integration: 'live',
    description: 'Extension hub — display names, DIDs, devices, and provisioning.',
    breadcrumb: ['Extensions'],
    apiEndpoints: ['/v1/tenant/extensions/hub'],
    primary: true,
  },
  {
    id: 'dashboard',
    label: 'Home',
    href: '/dashboard',
    group: 'operations',
    section: 'dashboard',
    icon: LayoutDashboard,
    permission: PERMISSIONS.TENANT_DASHBOARD_READ,
    integration: 'live',
    description: 'PBX overview and KPIs.',
    breadcrumb: ['Dashboard', 'Home'],
    apiEndpoints: ['/v1/tenant/dashboard'],
  },
  {
    id: 'organization-company',
    label: 'Company',
    href: '/organization/company',
    group: 'platform',
    section: 'organization',
    icon: Building2,
    permission: PERMISSIONS.TENANT_SETTINGS_READ,
    integration: 'live',
    description: 'Company profile, branding, and defaults.',
    breadcrumb: ['Organization', 'Company'],
    apiEndpoints: ['/v1/tenant/organization/company'],
  },
  {
    id: 'organization-sites',
    label: 'Sites',
    href: '/organization/sites',
    group: 'platform',
    section: 'organization',
    icon: Building2,
    permission: PERMISSIONS.TENANT_SETTINGS_READ,
    integration: 'live',
    description: 'Physical sites, addresses, and business hours.',
    breadcrumb: ['Organization', 'Sites'],
    apiEndpoints: ['/v1/tenant/organization/sites'],
  },
  {
    id: 'organization-departments',
    label: 'Departments',
    href: '/organization/departments',
    group: 'platform',
    section: 'organization',
    icon: Users,
    permission: PERMISSIONS.TENANT_USERS_READ,
    integration: 'live',
    description: 'Organizational departments.',
    breadcrumb: ['Organization', 'Departments'],
    apiEndpoints: ['/v1/tenant/organization/departments'],
  },
  {
    id: 'users',
    label: 'Users',
    href: '/people/users',
    group: 'platform',
    section: 'people',
    icon: Users,
    permission: PERMISSIONS.TENANT_USERS_READ,
    integration: 'live',
    description: 'User accounts and roles.',
    breadcrumb: ['People', 'Users'],
    apiEndpoints: ['/v1/tenant/users'],
  },
  {
    id: 'extensions-legacy',
    label: 'Extensions',
    href: '/people/extensions',
    group: 'telephony',
    section: 'people',
    icon: Phone,
    permission: PERMISSIONS.TENANT_EXTENSIONS_READ,
    integration: 'live',
    description: 'Extension numbers and line settings.',
    breadcrumb: ['People', 'Extensions'],
    apiEndpoints: ['/v1/tenant/extensions'],
    hiddenFromNav: true,
  },
  {
    id: 'devices',
    label: 'Devices',
    href: '/people/devices',
    group: 'telephony',
    section: 'people',
    icon: Smartphone,
    permission: PERMISSIONS.TENANT_DEVICES_READ,
    integration: 'live',
    description: 'Desk phones, softphones, and provisioning.',
    breadcrumb: ['People', 'Devices'],
    apiEndpoints: ['/v1/tenant/devices', '/v1/tenant/provisioning'],
    hiddenFromNav: true,
  },
  {
    id: 'provision-employee',
    label: 'Provision Employee',
    href: '/people/provision',
    group: 'telephony',
    section: 'people',
    icon: Users,
    permission: PERMISSIONS.TENANT_USERS_WRITE,
    integration: 'live',
    description: 'Guided workflow: user → extension → device → DID → voicemail.',
    breadcrumb: ['People', 'Provision Employee'],
    apiEndpoints: ['/v1/tenant/provision'],
    hiddenFromNav: true,
  },
  {
    id: 'my-numbers',
    label: 'My Numbers',
    href: '/phone-numbers/my-numbers',
    group: 'carrier',
    section: 'phone-numbers',
    icon: Phone,
    permission: PERMISSIONS.TENANT_DIDS_READ,
    integration: 'live',
    description: 'Assigned and unassigned DIDs with routing assignment.',
    breadcrumb: ['Phone Numbers', 'My Numbers'],
    apiEndpoints: ['/v1/tenant/dids'],
    hiddenFromNav: true,
  },
  {
    id: 'number-requests',
    label: 'Number Requests',
    href: '/phone-numbers/requests',
    group: 'carrier',
    section: 'phone-numbers',
    icon: PhoneForwarded,
    permission: PERMISSIONS.TENANT_NUMBERS_REQUEST,
    integration: 'live',
    description: 'Request numbers from platform inventory.',
    breadcrumb: ['Phone Numbers', 'Number Requests'],
    apiEndpoints: ['/v1/tenant/number-requests'],
  },
  {
    id: 'did-routing',
    label: 'DID Routing',
    href: '/phone-numbers/routing',
    group: 'carrier',
    section: 'phone-numbers',
    icon: Route,
    permission: PERMISSIONS.TENANT_DIDS_READ,
    integration: 'live',
    description: 'Visual overview of DID routing destinations.',
    breadcrumb: ['Phone Numbers', 'DID Routing'],
    apiEndpoints: ['/v1/tenant/dids', '/v1/tenant/routing/inbound'],
  },
  {
    id: 'ivr',
    label: 'IVR',
    href: '/call-flow/ivr',
    group: 'routing',
    section: 'call-flow',
    icon: Workflow,
    permission: PERMISSIONS.TENANT_IVR_READ,
    integration: 'live',
    description: 'Interactive voice response and auto attendant.',
    breadcrumb: ['Call Flow', 'IVR'],
    apiEndpoints: ['/v1/tenant/ivrs'],
  },
  {
    id: 'ring-groups',
    label: 'Ring Groups',
    href: '/call-flow/ring-groups',
    group: 'routing',
    section: 'call-flow',
    icon: PhoneForwarded,
    permission: PERMISSIONS.TENANT_ROUTING_READ,
    integration: 'live',
    description: 'Simultaneous and sequential ring groups.',
    breadcrumb: ['Call Flow', 'Ring Groups'],
    apiEndpoints: ['/v1/tenant/ring-groups'],
  },
  {
    id: 'queues',
    label: 'Queues',
    href: '/call-flow/queues',
    group: 'routing',
    section: 'call-flow',
    icon: ListOrdered,
    permission: PERMISSIONS.TENANT_QUEUES_READ,
    integration: 'live',
    description: 'Call queue configuration and agents.',
    breadcrumb: ['Call Flow', 'Queues'],
    apiEndpoints: ['/v1/tenant/queues'],
  },
  {
    id: 'time-conditions',
    label: 'Time Conditions',
    href: '/call-flow/time-conditions',
    group: 'routing',
    section: 'call-flow',
    icon: Clock,
    permission: PERMISSIONS.TENANT_ROUTING_READ,
    integration: 'live',
    description: 'Business hours routing rules.',
    breadcrumb: ['Call Flow', 'Time Conditions'],
    apiEndpoints: ['/v1/tenant/time-conditions'],
  },
  {
    id: 'holidays',
    label: 'Holidays',
    href: '/call-flow/holidays',
    group: 'routing',
    section: 'call-flow',
    icon: Calendar,
    permission: PERMISSIONS.TENANT_ROUTING_READ,
    integration: 'live',
    description: 'Holiday calendars for call routing.',
    breadcrumb: ['Call Flow', 'Holidays'],
    apiEndpoints: ['/v1/tenant/holiday-calendars'],
  },
  {
    id: 'incoming-routes',
    label: 'Incoming Routes',
    href: '/call-flow/incoming-routes',
    group: 'routing',
    section: 'call-flow',
    icon: Route,
    permission: PERMISSIONS.TENANT_ROUTING_READ,
    integration: 'live',
    description: 'Advanced inbound routing policies.',
    breadcrumb: ['Call Flow', 'Incoming Routes'],
    apiEndpoints: ['/v1/tenant/routing/inbound'],
  },
  {
    id: 'outgoing-routes',
    label: 'Outgoing Routes',
    href: '/call-flow/outgoing-routes',
    group: 'routing',
    section: 'call-flow',
    icon: Network,
    permission: PERMISSIONS.TENANT_ROUTING_READ,
    integration: 'live',
    description: 'Outbound dial plans and trunk selection.',
    breadcrumb: ['Call Flow', 'Outgoing Routes'],
    apiEndpoints: ['/v1/tenant/routing/outbound'],
  },
  {
    id: 'voicemail',
    label: 'Voicemail',
    href: '/communication/voicemail',
    group: 'routing',
    section: 'communication',
    icon: Voicemail,
    permission: PERMISSIONS.TENANT_VOICEMAIL_READ,
    integration: 'live',
    description: 'Voicemail boxes and greetings.',
    breadcrumb: ['Communication', 'Voicemail'],
    apiEndpoints: ['/v1/tenant/voicemail'],
  },
  {
    id: 'conferences',
    label: 'Conference Rooms',
    href: '/communication/conferences',
    group: 'routing',
    section: 'communication',
    icon: Radio,
    permission: PERMISSIONS.TENANT_CONFERENCES_READ,
    integration: 'live',
    description: 'Audio conference bridges.',
    breadcrumb: ['Communication', 'Conference Rooms'],
    apiEndpoints: ['/v1/tenant/conferences'],
  },
  {
    id: 'paging',
    label: 'Paging',
    href: '/communication/paging',
    group: 'operations',
    section: 'communication',
    icon: Megaphone,
    permission: PERMISSIONS.TENANT_PAGING_READ,
    integration: 'live',
    description: 'Paging and intercom endpoints.',
    breadcrumb: ['Communication', 'Paging'],
    apiEndpoints: ['/v1/tenant/paging'],
  },
  {
    id: 'announcements',
    label: 'Announcements',
    href: '/communication/announcements',
    group: 'routing',
    section: 'communication',
    icon: Volume2,
    permission: PERMISSIONS.TENANT_IVR_READ,
    integration: 'live',
    description: 'System announcements and prompts.',
    breadcrumb: ['Communication', 'Announcements'],
    apiEndpoints: ['/v1/tenant/audio/announcements'],
  },
  {
    id: 'music-on-hold',
    label: 'Music on Hold',
    href: '/communication/music-on-hold',
    group: 'routing',
    section: 'communication',
    icon: Volume2,
    permission: PERMISSIONS.TENANT_IVR_READ,
    integration: 'live',
    description: 'Music on hold playlists.',
    breadcrumb: ['Communication', 'Music on Hold'],
    apiEndpoints: ['/v1/tenant/audio/moh'],
  },
  {
    id: 'cdr',
    label: 'CDR',
    href: '/reports/cdr',
    group: 'analytics',
    section: 'reports',
    icon: FileText,
    permission: PERMISSIONS.TENANT_CDR_READ,
    integration: 'live',
    description: 'Call detail records.',
    breadcrumb: ['Reports', 'CDR'],
    apiEndpoints: ['/v1/tenant/cdr'],
  },
  {
    id: 'call-recordings',
    label: 'Recordings',
    href: '/reports/recordings',
    group: 'analytics',
    section: 'reports',
    icon: Mic,
    permission: PERMISSIONS.RECORDINGS_READ,
    integration: 'live',
    description: 'Call recording playback.',
    breadcrumb: ['Reports', 'Recordings'],
    apiEndpoints: ['/v1/tenant/recordings'],
  },
  {
    id: 'analytics',
    label: 'Analytics',
    href: '/reports/analytics',
    group: 'analytics',
    section: 'reports',
    icon: Activity,
    permission: PERMISSIONS.TENANT_REPORTS_READ,
    integration: 'live',
    description: 'Usage and quality analytics.',
    breadcrumb: ['Reports', 'Analytics'],
    apiEndpoints: ['/v1/tenant/cdr'],
  },
  {
    id: 'settings-pbx',
    label: 'PBX',
    href: '/settings/pbx',
    group: 'system',
    section: 'settings',
    icon: Settings,
    permission: PERMISSIONS.TENANT_SETTINGS_READ,
    integration: 'live',
    description: 'PBX configuration defaults.',
    breadcrumb: ['Settings', 'PBX'],
  },
  {
    id: 'settings-security',
    label: 'Security',
    href: '/settings/security',
    group: 'security',
    section: 'settings',
    icon: Shield,
    permission: PERMISSIONS.TENANT_SETTINGS_READ,
    integration: 'live',
    description: 'Security and session policies.',
    breadcrumb: ['Settings', 'Security'],
  },
  {
    id: 'settings-api-keys',
    label: 'API Keys',
    href: '/settings/api-keys',
    group: 'security',
    section: 'settings',
    icon: Key,
    permission: PERMISSIONS.TENANT_SETTINGS_READ,
    integration: 'live',
    description: 'Tenant API keys.',
    breadcrumb: ['Settings', 'API Keys'],
    apiEndpoints: ['/v1/tenant/api-keys'],
  },
  {
    id: 'supervisor',
    label: 'Supervisor',
    href: '/contact-center/supervisor',
    group: 'operations',
    section: 'contact-center',
    icon: Headphones,
    permission: PERMISSIONS.SUPERVISOR_DASHBOARD_READ,
    integration: 'live',
    description: 'Contact center supervisor console.',
    breadcrumb: ['Contact Center', 'Supervisor'],
    apiEndpoints: ['/v1/supervisor/dashboard'],
  },
  {
    id: 'reception',
    label: 'Reception',
    href: '/contact-center/reception',
    group: 'operations',
    section: 'contact-center',
    icon: PhoneForwarded,
    permission: PERMISSIONS.TENANT_RECEPTION_READ,
    integration: 'live',
    description: 'Reception and operator console.',
    breadcrumb: ['Contact Center', 'Reception'],
    apiEndpoints: ['/v1/tenant/reception'],
  },
];

export const TENANT_NAV_V2_SECTION_ORDER = [
  'dashboard',
  'organization',
  'people',
  'phone-numbers',
  'call-flow',
  'communication',
  'reports',
  'settings',
  'contact-center',
] as const;

export type TenantNavSectionId = (typeof TENANT_NAV_V2_SECTION_ORDER)[number];

export const TENANT_NAV_V2_SECTION_LABELS: Record<TenantNavSectionId, string> = {
  dashboard: 'Dashboard',
  organization: 'Organization',
  people: 'People',
  'phone-numbers': 'Phone Numbers',
  'call-flow': 'Call Flow',
  communication: 'Communication',
  reports: 'Reports',
  settings: 'Settings',
  'contact-center': 'Contact Center',
};

export function buildTenantNavV2Sections(filteredModules: ModuleDefinition[]): TenantNavSection[] {
  return TENANT_NAV_V2_SECTION_ORDER.map((sectionId) => ({
    id: sectionId,
    label: TENANT_NAV_V2_SECTION_LABELS[sectionId],
    items: filteredModules.filter((m) => m.section === sectionId),
  })).filter((s) => s.items.length > 0);
}
