import {
  Activity,
  Building2,
  FileText,
  LayoutDashboard,
  ListOrdered,
  Mic,
  Network,
  Phone,
  PhoneForwarded,
  Radio,
  Route,
  Server,
  Settings,
  Smartphone,
  Users,
  Voicemail,
  Workflow,
} from 'lucide-react';
import type { ModuleDefinition } from '../../types/navigation';
import { PERMISSIONS } from '../rbac/permissions';

export const TENANT_MODULES: ModuleDefinition[] = [
  {
    id: 'dashboard',
    label: 'Tenant Dashboard',
    href: '/dashboard',
    group: 'operations',
    icon: LayoutDashboard,
    permission: PERMISSIONS.TENANT_DASHBOARD_READ,
    integration: 'live',
    description: 'Tenant operations snapshot — calls, extensions, and devices.',
    breadcrumb: ['Tenant', 'Dashboard'],
    apiEndpoints: ['/v1/tenant/dashboard'],
  },
  {
    id: 'organization',
    label: 'Organization',
    href: '/organization',
    group: 'platform',
    icon: Building2,
    permission: PERMISSIONS.TENANT_SETTINGS_READ,
    integration: 'live',
    description: 'Current tenant profile, sites, and organization settings.',
    breadcrumb: ['Platform', 'Organization'],
  },
  {
    id: 'users',
    label: 'Users',
    href: '/users',
    group: 'platform',
    icon: Users,
    permission: PERMISSIONS.TENANT_USERS_READ,
    integration: 'live',
    description: 'User accounts, profiles, and site assignments.',
    breadcrumb: ['Platform', 'Users'],
    apiEndpoints: ['/v1/tenant/users'],
  },
  {
    id: 'extensions',
    label: 'Extensions',
    href: '/extensions',
    group: 'telephony',
    icon: Phone,
    permission: PERMISSIONS.TENANT_EXTENSIONS_READ,
    integration: 'live',
    description: 'Extension numbers, line assignments, and dial plans.',
    breadcrumb: ['PBX', 'Extensions'],
    apiEndpoints: ['/v1/tenant/extensions'],
  },
  {
    id: 'devices',
    label: 'Devices',
    href: '/devices',
    group: 'telephony',
    icon: Smartphone,
    permission: PERMISSIONS.TENANT_DEVICES_READ,
    integration: 'live',
    description: 'Desk phones, registrations, firmware, and MAC inventory.',
    breadcrumb: ['PBX', 'Devices'],
    apiEndpoints: ['/v1/tenant/devices'],
  },
  {
    id: 'sip-accounts',
    label: 'SIP Registrations',
    href: '/sip-accounts',
    group: 'telephony',
    icon: Network,
    permission: PERMISSIONS.TENANT_DEVICES_READ,
    integration: 'live',
    description: 'SIP endpoint credentials and live registration status.',
    breadcrumb: ['PBX', 'SIP Registrations'],
    apiEndpoints: ['/v1/tenant/devices'],
  },
  {
    id: 'provisioning',
    label: 'Provisioning',
    href: '/provisioning',
    group: 'telephony',
    icon: Server,
    permission: PERMISSIONS.PROVISIONING_ADMIN,
    integration: 'live',
    description: 'Zero-touch provisioning, templates, and firmware rollout.',
    breadcrumb: ['PBX', 'Provisioning'],
    apiEndpoints: ['/v1/provisioning/devices/enroll'],
  },
  {
    id: 'dids',
    label: 'Phone Numbers',
    href: '/dids',
    group: 'carrier',
    icon: Phone,
    permission: PERMISSIONS.TENANT_DIDS_READ,
    integration: 'live',
    description: 'Numbers assigned to this tenant — extensions, IVR, and queue routing.',
    breadcrumb: ['Carrier & Numbers', 'DIDs'],
    apiEndpoints: ['/v1/tenant/dids'],
  },
  {
    id: 'call-routing',
    label: 'Call Routing',
    href: '/call-routing',
    group: 'routing',
    icon: Route,
    permission: PERMISSIONS.TENANT_ROUTING_READ,
    integration: 'live',
    description: 'Inbound/outbound routing rules and time-based routing.',
    breadcrumb: ['Call Routing', 'Rules'],
    apiEndpoints: ['/v1/tenant/routing/policies'],
  },
  {
    id: 'ring-groups',
    label: 'Ring Groups',
    href: '/ring-groups',
    group: 'routing',
    icon: PhoneForwarded,
    permission: PERMISSIONS.TENANT_ROUTING_READ,
    integration: 'live',
    description: 'Simultaneous and sequential ring group configuration.',
    breadcrumb: ['Call Routing', 'Ring Groups'],
    apiEndpoints: ['/v1/tenant/ring-groups'],
  },
  {
    id: 'queues',
    label: 'Queues',
    href: '/queues',
    group: 'routing',
    icon: ListOrdered,
    permission: PERMISSIONS.TENANT_QUEUES_READ,
    integration: 'live',
    description: 'Call queue configuration, agents, and strategies.',
    breadcrumb: ['Call Routing', 'Queues'],
    apiEndpoints: ['/v1/tenant/queues'],
  },
  {
    id: 'ivr',
    label: 'IVR',
    href: '/ivr',
    group: 'routing',
    icon: Workflow,
    permission: PERMISSIONS.TENANT_IVR_READ,
    integration: 'live',
    description: 'Interactive voice response menus and call flows.',
    breadcrumb: ['Call Routing', 'IVR'],
    apiEndpoints: ['/v1/tenant/ivrs'],
  },
  {
    id: 'voicemail',
    label: 'Voicemail',
    href: '/voicemail',
    group: 'routing',
    icon: Voicemail,
    permission: PERMISSIONS.TENANT_VOICEMAIL_READ,
    integration: 'live',
    description: 'Voicemail boxes, greetings, and notification settings.',
    breadcrumb: ['Call Routing', 'Voicemail'],
    apiEndpoints: ['/v1/tenant/voicemail'],
  },
  {
    id: 'conferences',
    label: 'Conferences',
    href: '/conferences',
    group: 'routing',
    icon: Radio,
    permission: PERMISSIONS.TENANT_ADMIN,
    integration: 'live',
    description: 'Audio conference bridges and participant management.',
    breadcrumb: ['Call Routing', 'Conferences'],
  },
  {
    id: 'cdr',
    label: 'CDR',
    href: '/cdr',
    group: 'analytics',
    icon: FileText,
    permission: PERMISSIONS.TENANT_CDR_READ,
    integration: 'live',
    description: 'Call detail records with direction, duration, and disposition.',
    breadcrumb: ['Analytics', 'CDR'],
    apiEndpoints: ['/v1/tenant/cdr'],
  },
  {
    id: 'call-recordings',
    label: 'Recordings',
    href: '/call-recordings',
    group: 'analytics',
    icon: Mic,
    permission: PERMISSIONS.RECORDINGS_READ,
    integration: 'live',
    description: 'Browse and playback call recordings.',
    breadcrumb: ['Analytics', 'Recordings'],
    apiEndpoints: ['/v1/tenant/recordings'],
  },
  {
    id: 'reports',
    label: 'Reports',
    href: '/reports',
    group: 'analytics',
    icon: Activity,
    permission: PERMISSIONS.TENANT_REPORTS_READ,
    integration: 'live',
    description: 'Usage, quality, and operational reports.',
    breadcrumb: ['Analytics', 'Reports'],
    apiEndpoints: ['/v1/tenant/cdr'],
  },
  {
    id: 'settings',
    label: 'Settings',
    href: '/settings',
    group: 'system',
    icon: Settings,
    permission: PERMISSIONS.TENANT_SETTINGS_READ,
    integration: 'live',
    description: 'Portal preferences, features, and configuration.',
    breadcrumb: ['System', 'Settings'],
  },
];
